import { readFileSync, mkdirSync, writeFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

// Get the current directory path in ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Paths
const srcWasmDir = join(__dirname, '../src/wasm');
const publicWasmDir = join(__dirname, '../src/public/wasm');
const assetsWasmDir = join(__dirname, '../src/assets/wasm');

// Ensure the output directory exists
if (!existsSync(assetsWasmDir)) {
    mkdirSync(assetsWasmDir, { recursive: true });
}

// Try to find the input file in either src/wasm or src/public/wasm
let inputFile = '';
if (existsSync(join(srcWasmDir, 'index.js'))) {
    inputFile = join(srcWasmDir, 'index.js');
} else if (existsSync(join(publicWasmDir, 'index.js'))) {
    inputFile = join(publicWasmDir, 'index.js');
} else {
    console.error('Error: Could not find index.js in src/wasm/ or src/public/wasm/');
    process.exit(1);
}

const outputFile = join(assetsWasmDir, 'index.js');

// Read the original file
console.log(`Reading from: ${inputFile}`);
let content = readFileSync(inputFile, 'utf8');
console.log('Successfully read input file');

// Create the output content
const outputContent = `
// This file is auto-generated by transform-wasm-js.mjs
// It loads the WebAssembly module and provides a clean API

// The WASM module instance
let wasmInstance = null;

// Function to initialize the WASM module
export async function initWasm(imports = {}) {
  if (wasmInstance) return wasmInstance;

  try {
    // In development, use the public path, in production use the assets path
    const wasmUrl = import.meta.env.DEV 
      ? '/wasm/index.wasm' 
      : '/assets/wasm/index.wasm';
    
    // Fetch and instantiate the WASM module
    const response = await fetch(wasmUrl);
    const wasmBuffer = await response.arrayBuffer();
    
    // Import the WASM module
    const wasmModule = await WebAssembly.instantiate(wasmBuffer, {
      env: {
        ...imports,
        // Add any required environment functions here
      },
      // Add any other required imports here
    });
    
    wasmInstance = wasmModule.instance;
    return wasmInstance;
  } catch (error) {
    console.error('Failed to load WASM module:', error);
    throw error;
  }
}

// Export the initialization function
export default initWasm;`;

// Write the transformed content to the output file
try {
  writeFileSync(outputFile, outputContent, 'utf8');
  console.log('Successfully wrote transformed WASM loader to:', outputFile);
} catch (error) {
  console.error('Error writing output file:', error);
  process.exit(1);
}

// WebAssembly module loader
export default function(Module = {}) {
  return new Promise((resolve, reject) => {
    const script = document.createElement('script');
    script.type = 'module';
    script.onload = () => {
      if (window.Module) {
        resolve(window.Module);
      } else {
        reject(new Error('Failed to initialize WebAssembly module'));
      }
    };
    script.onerror = (error) => {
      console.error('Script load error:', error);
      reject(error);
    };
    
    // Add the Module configuration
    window.Module = {
      ...Module,
      locateFile: (path) => {
        if (path.endsWith('.wasm')) {
          return '/wasm/index.wasm';
        }
        return path;
      },
      onRuntimeInitialized: () => {
        if (Module.onRuntimeInitialized) {
          Module.onRuntimeInitialized();
        }
        resolve(window.Module);
      },
      onAbort: (error) => {
        console.error('WebAssembly module aborted:', error);
        reject(error);
      }
    };
    
    // Create a blob URL for the script
    const scriptContent = content
      .replace(/\./g, '\\.')
      .replace(/\*/g, '\\*')
      .replace(/\$/g, '\\$')
      .replace(/\^/g, '\\^')
      .replace(/\[/g, '\\[')
      .replace(/\]/g, '\\]')
      .replace(/\(/g, '\\(')
      .replace(/\)/g, '\\)')
      .replace(/\{/g, '\\{')
      .replace(/\}/g, '\\}')
      .replace(/\?/g, '\\?')
      .replace(/\+/g, '\\+')
      .replace(/\|/g, '\\|')
      .replace(/import\.meta\.url/g, '"/wasm/index.js"')
      .replace(/new URL\('([^']*)\.wasm', import\.meta\.url\)/g, "'/wasm/index.wasm'");
    
    const blob = new Blob([scriptContent], { type: 'application/javascript' });
    script.src = URL.createObjectURL(blob);
    
    // Add to document
    document.head.appendChild(script);
  });
}

// Ensure the output directory exists
if (!existsSync(assetsWasmDir)) {
  mkdirSync(assetsWasmDir, { recursive: true });
}

// Write the transformed content to the output file
try {
  writeFileSync(outputFile, content, 'utf8');
  console.log('Successfully wrote transformed WASM loader to:', outputFile);
} catch (error) {
  console.error('Error writing output file:', error);
  process.exit(1);
}
